import type { NextPage } from "next";
import Head from "next/head";
import { classes } from "../utils/classes";
import Navbar from "../components/layout/Navbar/Navbar";
import { tailwind_config } from "../utils/twconf2js";
import AboutME from "../components/Homepage/AboutME/AboutME";
import MyTechStack from "../components/Homepage/MyTechStack/MyTechStack";
import MyProject from "../components/Homepage/MyProject/MyProject";
import Block from "../components/ui/Block/Block";
import HaveFun from "../components/Homepage/HaveFun/HaveFun";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes("flex flex-col items-center", "relative")}>
        <Navbar />
        <Block value={20} />
        {/* 關於我 */}
        <AboutME />
        <Block value={15} />
        {/* 遊樂場 */}
        <HaveFun />
        {/* 我的項目 */}
        {/* <MyProject /> */}
        {/* 我的技術棧 */}
        {/* <MyTechStack /> */}
        {/* 聯繫我 */}
      </main>
      <footer></footer>
    </div>
  );
};

export default Home;
