import type { NextPage } from "next";
import Head from "next/head";
import { classes } from "../utils/classes";
import { tailwind_config } from "../utils/twconf2js";
import AboutME from "../components/Homepage/AboutME/AboutME";
import MyTechStack from "../components/Homepage/MyTechStack/MyTechStack";
import MyProject from "../components/Homepage/MyProject/MyProject";
import Navbar from "../components/_Global/layout/Navbar/Navbar";
import Block from "../components/_Global/ui/Block/Block";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Dalufishe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={classes("flex flex-col items-center", "relative")}>
        <Navbar />
        <Block value={20} />
        {/* 關於我 */}
        <AboutME />
        <Block value={15} />
        <main className={classes("w-[85%]", "flex gap-3")}>
          {/* 我的技術棧 */}
          <MyTechStack />
          {/* 我的項目 */}
          {/* <MyProject /> */}
          {/* 聯繫我 */}
        </main>
      </div>
      <footer></footer>
    </div>
  );
};

export default Home;
