import type { NextPage } from "next";
import Head from "next/head";
import { classes } from "../utils/classes";
import Navbar from "../components/Navbar/Navbar";
import Image from "next/image";
import MyImage from "../assets/me.png";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes("flex flex-col items-center")}>
        <Navbar />
        {/* 關於我 */}
        <div
          className={classes(
            "w-full",
            "flex flex-col items-center",
            "mt-[80px]"
          )}
        >
          <Image
            className={classes(
              "rounded-full",
              "border-2 border-light",
              "bg-red-50"
            )}
            src={MyImage}
            alt="this is my photo"
            width={200}
            height={200}
          />
          <h2 className={classes("text-2xl")}>A Full Stack Web Developer</h2>
        </div>
        {/* 我的技術棧 */}
        {/* 我做的項目 */}
        {/* 聯繫我 */}
      </main>
      <footer></footer>
    </div>
  );
};

export default Home;
